ALTER SESSION SET CONTAINER = XEPDB1;
 
CREATE TABLESPACE EDIFF_DATA DATAFILE 'ediff_Datos.dbf' SIZE 100M AUTOEXTEND ON;
 
CREATE USER FinalBoss IDENTIFIED BY FinalBoss2029 DEFAULT TABLESPACE EDIFF_DATA TEMPORARY TABLESPACE TEMP;
 
GRANT CONNECT TO FinalBoss;
GRANT ALL PRIVILEGES TO FinalBoss;
 
ALTER USER FinalBoss QUOTA UNLIMITED ON EDIFF_DATA;