CREATE TABLE usuarios (
    id_usuario      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre          VARCHAR2(100) NOT NULL,
    correo          VARCHAR2(150) NOT NULL,
    fecha_registro  DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_usuarios PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuarios_correo UNIQUE (correo)
);

CREATE TABLE cuentas (
    id_cuenta       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario      NUMBER NOT NULL,
    nombre          VARCHAR2(100) NOT NULL,
    tipo            VARCHAR2(20) NOT NULL,
    saldo_inicial   NUMBER(12,2) DEFAULT 0 NOT NULL,
    activa          CHAR(1) DEFAULT 'S' NOT NULL,

    CONSTRAINT pk_cuentas PRIMARY KEY (id_cuenta),

    CONSTRAINT fk_cuentas_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario),

    CONSTRAINT ck_cuentas_tipo
        CHECK (tipo IN ('EFECTIVO', 'BANCO', 'TARJETA')),

    CONSTRAINT ck_cuentas_activa
        CHECK (activa IN ('S', 'N'))
);

CREATE TABLE movimientos (
    id_movimiento   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    id_cuenta       NUMBER NOT NULL,
    fecha           DATE DEFAULT SYSDATE NOT NULL,
    tipo            VARCHAR2(10) NOT NULL,
    categoria       VARCHAR2(80) NOT NULL,
    descripcion     VARCHAR2(300),
    monto           NUMBER(12,2) NOT NULL,

    CONSTRAINT pk_movimientos PRIMARY KEY (id_movimiento),

    CONSTRAINT fk_movimientos_cuenta
        FOREIGN KEY (id_cuenta)
        REFERENCES cuentas(id_cuenta),

    CONSTRAINT ck_movimientos_tipo
        CHECK (tipo IN ('INGRESO', 'GASTO')),

    CONSTRAINT ck_movimientos_monto
        CHECK (monto > 0)
);